"""add property

Revision ID: 443e80fcecc4
Revises: 9cc6f678edaa
Create Date: 2024-03-07 12:59:16.235859

"""


# revision identifiers, used by Alembic.
revision = "443e80fcecc4"
down_revision = "9cc6f678edaa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
