"""Add path field to user

Revision ID: 546cd4dc1bb0
Revises: 7aa4536a889e
Create Date: 2024-04-11 13:21:21.178512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '546cd4dc1bb0'
down_revision = '7aa4536a889e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_path')
    # ### end Alembic commands ###
