"""User and workout fields

Revision ID: 7aa4536a889e
Revises: 443e80fcecc4
Create Date: 2024-04-05 17:09:13.402187

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7aa4536a889e'
down_revision = '443e80fcecc4'
branch_labels = None
depends_on = None


def _get_type_enum():
    return postgresql.ENUM(
        "USER_LIKED",
        "TOP_CHART",
        "USER_CREATED",
        "ADMIN_CREATED",
        "NEW_RELEASES",
        "RECENTLY_PLAYED",
        "EXCLUSIVE_RELEASES",
        "RECOMMENDED",
        "COLLECTIONS",
        name="typeenum",
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    type_enum = _get_type_enum()
    type_enum.create(op.get_bind())
    op.add_column('users', sa.Column('score_level', type_enum, nullable=True))
    op.add_column('exercises', sa.Column('calories', sa.Float(), nullable=True))
    op.create_index(op.f('ix_user_measurements_user_id'), 'user_measurements', ['user_id'], unique=False)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('age', sa.BigInteger(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('score', sa.BigInteger(), nullable=True))
    op.add_column('workouts', sa.Column('is_done', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workouts', 'is_done')
    op.drop_column('users', 'score_level')
    op.drop_column('users', 'score')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'age')
    op.drop_column('users', 'name')
    op.drop_index(op.f('ix_user_measurements_user_id'), table_name='user_measurements')
    op.drop_column('exercises', 'calories')
    type_enum = _get_type_enum()
    type_enum.drop(op.get_bind())
    # ### end Alembic commands ###