"""remove enum

Revision ID: 7d724445155f
Revises: abd89287f888
Create Date: 2024-04-16 14:44:17.119466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d724445155f'
down_revision = 'abd89287f888'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
