"""Add hashed_password column to users table

Revision ID: 828376422486
Revises: f9ea7a54a847
Create Date: 2024-03-05 12:12:24.280330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828376422486'
down_revision = 'f9ea7a54a847'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
