"""rename fields

Revision ID: 9cc6f678edaa
Revises: 828376422486
Create Date: 2024-03-07 12:41:28.870976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9cc6f678edaa"
down_revision = "828376422486"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("exercises", sa.Column("description", sa.String(), nullable=True))
    op.alter_column(
        "user_measurements",
        "weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "user_measurements",
        "height",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "user_measurements",
        "biceps",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "user_measurements",
        "waist",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.alter_column(
        "user_measurements",
        "hips",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.add_column("workouts", sa.Column("name", sa.String(), nullable=True))
    op.add_column("workouts", sa.Column("description", sa.String(), nullable=True))
    op.add_column("workouts", sa.Column("workout_date", sa.Date(), nullable=True))
    op.add_column("workouts", sa.Column("workout_time", sa.Time(), nullable=True))
    op.add_column("workouts", sa.Column("user_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "workouts", "users", ["user_id"], ["id"])
    op.drop_column("workouts", "date")
    op.drop_column("workouts", "time")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "workouts", sa.Column("time", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "workouts", sa.Column("date", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "workouts", type_="foreignkey")
    op.drop_column("workouts", "user_id")
    op.drop_column("workouts", "workout_time")
    op.drop_column("workouts", "workout_date")
    op.drop_column("workouts", "description")
    op.drop_column("workouts", "name")
    op.alter_column(
        "user_measurements",
        "hips",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "user_measurements",
        "waist",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "user_measurements",
        "biceps",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "user_measurements",
        "height",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "user_measurements",
        "weight",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.drop_column("exercises", "description")
    # ### end Alembic commands ###
